/**
 * CCTX-023: Prompt builder with pinned layer.
 *
 * Frozen zone order:
 *   system → verified TaskContract → validated typed snapshot → narrative
 *   bridge → recall guide → recent verbatim atomic tail → current user input
 *   → exact recall blocks.
 *
 * The Current Focus View is generated by deterministic code and only
 * references IDs that already exist in the snapshot. When compaction is off,
 * buildPassthroughPrompt returns the original history path untouched.
 */

import type { EventEnvelope, StructuredSnapshot, TaskContract, TokenStats } from "./types.ts";

/** Structural view of the task ledger used by the pinned layer renderer. */
export interface TaskLedgerLike {
	getFocusTask(): import("./task-ledger.ts").LedgerTask | undefined;
	/** Optional for backwards-compatible renderers; enables cross-task constraints. */
	getTask?(taskId: string): import("./task-ledger.ts").LedgerTask | undefined;
	nonTerminalIndex(): { taskId: string; status: string; goal: string; blockers: string[]; version: number }[];
	getPendingGoalChanges(): { candidateTaskIds: string[]; reason: string; sourceEventId: string }[];
}

/** Ledger surface needed when binding and validating a frozen snapshot ref. */
export interface VersionedTaskLedgerLike extends TaskLedgerLike {
	getFocusTaskId(): string | undefined;
	getLedgerVersion(): number;
	getTask(taskId: string): import("./task-ledger.ts").LedgerTask | undefined;
}

export type ZoneKind =
	| "contract"
	| "snapshot"
	| "narrative"
	| "recallGuide"
	| "recentTail"
	| "currentInput"
	| "exactRecall";

export interface PromptSection {
	zone: ZoneKind;
	text: string;
	tokens: number;
}

export interface BuiltPrompt {
	systemPrompt: string;
	sections: PromptSection[];
	tokenStats: TokenStats;
}

export interface PromptBuilderInput {
	systemPrompt: string;
	/** Global contract. When a ledger is supplied it is rendered with the live focused task layer. */
	contract?: TaskContract;
	ledger?: TaskLedgerLike;
	snapshot?: StructuredSnapshot;
	/** Overrides snapshot.narrative when provided. */
	narrative?: string;
	recallGuide?: string;
	tailEvents: EventEnvelope[];
	currentInput: string;
	exactRecall: string[];
	toolsTokenEstimate?: number;
	outputReserveTokens?: number;
	estimateTextTokens?: (text: string) => number;
}

function defaultEstimate(text: string): number {
	return Math.ceil(text.length / 4);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function blocksToText(blocks: unknown[]): string {
	const parts: string[] = [];
	for (const block of blocks) {
		if (!isRecord(block)) continue;
		if (block.type === "text" && typeof block.text === "string") parts.push(block.text);
		else if (block.type === "thinking" && typeof block.thinking === "string") parts.push(block.thinking);
		else if (block.type === "toolCall") {
			parts.push(`[tool call: ${String(block.name)}(${canonicalish(block.arguments)})]`);
		}
	}
	return parts.join("\n");
}

function canonicalish(value: unknown): string {
	try {
		return JSON.stringify(value) ?? "";
	} catch {
		return "";
	}
}

function eventText(event: EventEnvelope): string {
	if (typeof event.payload === "string") return event.payload;
	if (isRecord(event.payload)) {
		if (event.eventType === "tool_call" && typeof event.payload.name === "string") {
			return `[tool call: ${event.payload.name}(${canonicalish(event.payload.arguments)})]`;
		}
		if (typeof event.payload.text === "string") return event.payload.text;
		if (typeof event.payload.content === "string") return event.payload.content;
		if (Array.isArray(event.payload.content)) return blocksToText(event.payload.content);
		if (isRecord(event.payload.message)) return eventText({ ...event, payload: event.payload.message });
	}
	if (event.payloadRef) return `[offloaded content: ${event.payloadRef}]`;
	return "";
}

/**
 * Layered pinned injection (design correction 2026-08-22): global contract +
 * current focus task contract in full + non-terminal task index + pending
 * goal changes. What is pinned is the RE-INJECTION MECHANISM and its
 * authority, not frozen content.
 */
export function renderPinnedLedgerLayer(ledger: TaskLedgerLike, globalContract?: TaskContract): string {
	const parts: string[] = [];
	if (globalContract) {
		parts.push(renderContract(globalContract, true));
	}
	const focus = ledger.getFocusTask();
	if (focus) {
		const sourceRefs = new Set([
			...focus.goal.verbatimSourceEventIds,
			focus.provenance.createdFromEvent,
			...focus.provenance.updatedFromEvents,
		]);
		const lines = [
			`# Current focus task ${focus.taskId} (contract v${focus.version}, status ${focus.status})`,
			`Task ref: task://${focus.taskId}/v${focus.version}`,
			`Goal: ${focus.goal.normalized}`,
			`Goal scope: ${focus.goal.scope?.join(", ") || "(none)"}`,
			`Goal exclusions: ${focus.goal.exclusions?.join(", ") || "(none)"}`,
			"## Acceptance criteria",
			...(focus.acceptanceCriteria.length > 0 ? focus.acceptanceCriteria.map((c) => `- ${c}`) : ["- (none)"]),
			"## Task constraints",
			...(focus.constraints.length > 0 ? focus.constraints.map((c) => `- [${c.kind}] ${c.text}`) : ["- (none)"]),
			"## Task permissions",
			`- allow: ${focus.permissions.allow.join(", ") || "(none)"}`,
			`- deny: ${focus.permissions.deny.join(", ") || "(none)"}`,
			`- approval required: ${focus.permissions.approvalRequired.join(", ") || "(none)"}`,
			"## Task budgets",
			...renderBudgetLines(focus.budgets),
			"## Output contract",
			focus.outputContract ?? "(none)",
			"## Blockers",
			...(focus.blockers.length > 0 ? focus.blockers.map((b) => `- ${b}`) : ["- (none)"]),
			"## Relations",
			`- parent: ${focus.relations.parentTaskId ?? "(none)"}`,
			`- depends on: ${focus.relations.dependsOn.join(", ") || "(none)"}`,
			`- supersedes: ${focus.relations.supersedes ?? "(none)"}`,
			"## Provenance",
			`- created by: ${focus.provenance.createdBy.kind}:${focus.provenance.createdBy.id} (verified=${focus.provenance.createdBy.verified})`,
			`- created at: ${focus.createdAt}`,
			`- updated at: ${focus.updatedAt}`,
			`- events: ${[...sourceRefs].filter(Boolean).join(", ") || "(none)"}`,
		];
		parts.push(lines.join("\n"));
	}
	const index = ledger.nonTerminalIndex().filter((t) => t.taskId !== focus?.taskId);
	if (index.length > 0) {
		const crossTaskConstraints = index.flatMap((entry) => {
			const task = ledger.getTask?.(entry.taskId);
			return (task?.constraints ?? []).map(
				(constraint) => `- ${entry.taskId}: [${constraint.kind}] ${constraint.text}`,
			);
		});
		if (crossTaskConstraints.length > 0) {
			parts.push(["# Cross-task constraints from other open tasks", ...crossTaskConstraints].join("\n"));
		}
		parts.push(
			[
				"# Other open tasks (index only — recall for details)",
				...index.map(
					(t) =>
						`- ${t.taskId} [${t.status}] v${t.version}: ${t.goal}${t.blockers.length ? ` (blockers: ${t.blockers.join("; ")})` : ""}`,
				),
			].join("\n"),
		);
	}
	const pending = ledger.getPendingGoalChanges();
	if (pending.length > 0) {
		parts.push(
			[
				"# Pending goal changes (unconfirmed — do not act on them)",
				...pending.map(
					(p) =>
						`- ${p.reason} (candidates: ${p.candidateTaskIds.join(", ") || "none"}; source ${p.sourceEventId})`,
				),
			].join("\n"),
		);
	}
	return parts.join("\n\n");
}

function renderBudgetLines(budgets: TaskContract["budgets"]): string[] {
	return [
		`- max tokens: ${budgets.maxTokens ?? "(none)"}`,
		`- max tool calls: ${budgets.maxToolCalls ?? "(none)"}`,
		`- max duration ms: ${budgets.maxDurationMs ?? "(none)"}`,
	];
}

function renderContract(contract: TaskContract, global = false): string {
	const lines = [
		`# ${global ? "Global Contract" : "Task Contract"} (version ${contract.version}, id ${contract.contractId})`,
		global ? `Legacy session goal (non-authoritative): ${contract.goal}` : `Goal: ${contract.goal}`,
		...(contract.derivedGoal ? [`Working goal (auto-derived, unconfirmed): ${contract.derivedGoal.text}`] : []),
		"",
		"## Acceptance criteria",
		...contract.acceptanceCriteria.map((c) => `- ${c}`),
		"",
		"## Constraints (always active)",
		...contract.constraints.map((c) => `- [${c.kind}] ${c.text}`),
		"",
		"## Permissions",
		`- allow: ${contract.permissions.allow.join(", ") || "(none)"}`,
		`- deny: ${contract.permissions.deny.join(", ") || "(none)"}`,
		`- approval required: ${contract.permissions.approvalRequired.join(", ") || "(none)"}`,
		"",
		"## Budgets",
		...renderBudgetLines(contract.budgets),
	];
	if (contract.outputContract) {
		lines.push("", `## Output contract`, contract.outputContract);
	}
	return lines.join("\n");
}

/**
 * Deterministic Current Focus View: generated by code, references only IDs
 * present in the snapshot. Never invents facts.
 */
export function buildFocusView(snapshot: StructuredSnapshot): string {
	const lines: string[] = ["## Current focus"];
	const inProgress = snapshot.tasks.filter((t) => t.state === "in_progress");
	const blocked = snapshot.tasks.filter((t) => t.state === "blocked");
	const done = snapshot.tasks.filter((t) => t.state === "done");
	for (const t of inProgress) lines.push(`- in progress: ${t.title} (${t.id})`);
	for (const t of blocked)
		lines.push(`- blocked: ${t.title} (${t.id})${t.blockers.length ? ` — blockers: ${t.blockers.join("; ")}` : ""}`);
	if (done.length > 0) lines.push(`- done: ${done.map((t) => `${t.title} (${t.id})`).join(", ")}`);
	const unresolved = snapshot.errors.filter((e) => !e.resolved);
	for (const e of unresolved) lines.push(`- unresolved error: ${e.message} (${e.id})`);
	for (const n of snapshot.nextActions) lines.push(`- next: ${n.text} (${n.id})`);
	if (snapshot.recallCatalogRefs.length > 0) {
		lines.push(`- recallable: ${snapshot.recallCatalogRefs.join(", ")}`);
	}
	return lines.join("\n");
}

function renderSnapshot(snapshot: StructuredSnapshot): string {
	const parts: string[] = [
		`# Verified state snapshot v${snapshot.snapshotVersion} (covers events through seq ${snapshot.baseEventSeq})`,
		buildFocusView(snapshot),
	];
	if (snapshot.facts.length > 0) {
		parts.push(
			"",
			"## Facts",
			...snapshot.facts.map((f) => `- ${f.verified ? "" : "[unverified] "}${f.text} (${f.id})`),
		);
	}
	if (snapshot.decisions.length > 0) {
		parts.push(
			"",
			"## Decisions",
			...snapshot.decisions.map((d) => `- ${d.text}${d.rationale ? ` — ${d.rationale}` : ""} (${d.id})`),
		);
	}
	if (snapshot.tools.length > 0) {
		parts.push(
			"",
			"## Tool states",
			...snapshot.tools.map(
				(t) =>
					`- ${t.name} [${t.toolCallId}]: ${t.state}${t.exitCode !== undefined ? ` (exit ${t.exitCode})` : ""}${t.resultRef ? ` ref ${t.resultRef}` : ""}`,
			),
		);
	}
	return parts.join("\n");
}

function renderTail(events: EventEnvelope[]): string {
	return events
		.map((e) => {
			const text = eventText(e);
			return text ? `[${e.seq} ${e.eventType}] ${text}` : `[${e.seq} ${e.eventType}]`;
		})
		.join("\n\n");
}

export function buildPrompt(input: PromptBuilderInput): BuiltPrompt {
	const estimate = input.estimateTextTokens ?? defaultEstimate;
	const sections: PromptSection[] = [];
	const push = (zone: ZoneKind, text: string) => {
		if (text.length === 0) return;
		sections.push({ zone, text, tokens: estimate(text) });
	};

	// Frozen order: contract → snapshot → narrative → recall guide → tail → input → recall.
	// With a task ledger, the contract zone is the live pinned projection so its
	// full token cost participates in both runtime projection and accounting.
	if (input.ledger) push("contract", renderPinnedLedgerLayer(input.ledger, input.contract));
	else if (input.contract) push("contract", renderContract(input.contract));
	if (input.snapshot) push("snapshot", renderSnapshot(input.snapshot));
	const narrative = input.narrative ?? input.snapshot?.narrative;
	if (narrative) push("narrative", `# Progress so far\n${narrative}`);
	if (input.recallGuide) push("recallGuide", input.recallGuide);
	if (input.tailEvents.length > 0) push("recentTail", renderTail(input.tailEvents));
	push("currentInput", input.currentInput);
	if (input.exactRecall.length > 0) push("exactRecall", input.exactRecall.join("\n\n"));

	const zoneTokens = (zone: ZoneKind) => sections.filter((s) => s.zone === zone).reduce((sum, s) => sum + s.tokens, 0);
	const tailImageTokens = input.tailEvents.reduce((sum, event) => {
		const payload = event.payload;
		if (!isRecord(payload)) return sum;
		const imageCount =
			typeof payload.imageCount === "number" ? payload.imageCount : payload.hasImages === true ? 1 : 0;
		return sum + imageCount * 1200;
	}, 0);
	const tokenStats: TokenStats = {
		system: estimate(input.systemPrompt),
		tools: input.toolsTokenEstimate ?? 0,
		contract: zoneTokens("contract"),
		snapshot: zoneTokens("snapshot"),
		narrative: zoneTokens("narrative"),
		recall: zoneTokens("recallGuide") + zoneTokens("exactRecall"),
		recentTail: zoneTokens("recentTail") + tailImageTokens,
		currentInput: zoneTokens("currentInput"),
		outputReserve: input.outputReserveTokens ?? 0,
		total: 0,
	};
	tokenStats.total =
		tokenStats.system +
		tokenStats.tools +
		tokenStats.contract +
		tokenStats.snapshot +
		tokenStats.narrative +
		tokenStats.recall +
		tokenStats.recentTail +
		tokenStats.currentInput +
		tokenStats.outputReserve;

	return { systemPrompt: input.systemPrompt, sections, tokenStats };
}

/**
 * Compaction-off passthrough: the original history path, untouched.
 */
export function buildPassthroughPrompt<TMessage>(
	systemPrompt: string,
	messages: TMessage[],
): { systemPrompt: string; messages: TMessage[] } {
	return { systemPrompt, messages };
}
