/**
 * CCTX-023: Prompt builder with pinned layer.
 *
 * Frozen zone order:
 *   system → verified TaskContract → validated typed snapshot → narrative
 *   bridge → recall guide → recent verbatim atomic tail → current user input
 *   → exact recall blocks.
 *
 * The Current Focus View is generated by deterministic code and only
 * references IDs that already exist in the snapshot. When compaction is off,
 * buildPassthroughPrompt returns the original history path untouched.
 */

import { PromptBudgetExceededError, selectBudgetedItems, truncateTextToBudget } from "./active-projection.ts";
import { buildAtomicGroups } from "./atomic-groups.ts";
import type {
	EventEnvelope,
	PromptZoneBudgets,
	StructuredSnapshot,
	TaskContract,
	TokenStats,
	ZoneProjectionStats,
} from "./types.ts";

/** Structural view of the task ledger used by the pinned layer renderer. */
export interface TaskLedgerLike {
	getFocusTask(): import("./task-ledger.ts").LedgerTask | undefined;
	/** Optional for backwards-compatible renderers; enables cross-task constraints. */
	getTask?(taskId: string): import("./task-ledger.ts").LedgerTask | undefined;
	nonTerminalIndex(): { taskId: string; status: string; goal: string; blockers: string[]; version: number }[];
	getPendingGoalChanges(): { candidateTaskIds: string[]; reason: string; sourceEventId: string }[];
}

/** Ledger surface needed when binding and validating a frozen snapshot ref. */
export interface VersionedTaskLedgerLike extends TaskLedgerLike {
	getFocusTaskId(): string | undefined;
	getLedgerVersion(): number;
	getTask(taskId: string): import("./task-ledger.ts").LedgerTask | undefined;
}

export type ZoneKind =
	| "contract"
	| "snapshot"
	| "narrative"
	| "recallGuide"
	| "recentTail"
	| "currentInput"
	| "exactRecall";

export interface PromptSection {
	zone: ZoneKind;
	text: string;
	tokens: number;
}

export interface BuiltPrompt {
	systemPrompt: string;
	sections: PromptSection[];
	tokenStats: TokenStats;
	projectionStats: ZoneProjectionStats[];
}

export interface PromptBuilderInput {
	systemPrompt: string;
	/** Global contract. When a ledger is supplied it is rendered with the live focused task layer. */
	contract?: TaskContract;
	ledger?: TaskLedgerLike;
	snapshot?: StructuredSnapshot;
	/** Overrides snapshot.narrative when provided. */
	narrative?: string;
	recallGuide?: string;
	tailEvents: EventEnvelope[];
	currentInput: string;
	exactRecall: string[];
	toolsTokenEstimate?: number;
	outputReserveTokens?: number;
	estimateTextTokens?: (text: string) => number;
	/** Hard budgets for mutable Hot/Warm/Recall zones. */
	zoneBudgets?: Partial<PromptZoneBudgets>;
	/** Measurement-only mode for the live pre-compaction provider tail. */
	enforceRecentTailBudget?: boolean;
}

export const DEFAULT_PROMPT_ZONE_BUDGETS: PromptZoneBudgets = {
	snapshot: 16_000,
	narrative: 4_000,
	recallGuide: 2_000,
	recentTail: 24_000,
	exactRecall: 8_000,
};

function defaultEstimate(text: string): number {
	return Math.ceil(text.length / 4);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}

function blocksToText(blocks: unknown[]): string {
	const parts: string[] = [];
	for (const block of blocks) {
		if (!isRecord(block)) continue;
		if (block.type === "text" && typeof block.text === "string") parts.push(block.text);
		else if (block.type === "thinking" && typeof block.thinking === "string") parts.push(block.thinking);
		else if (block.type === "toolCall") {
			parts.push(`[tool call: ${String(block.name)}(${canonicalish(block.arguments)})]`);
		}
	}
	return parts.join("\n");
}

function canonicalish(value: unknown): string {
	try {
		return JSON.stringify(value) ?? "";
	} catch {
		return "";
	}
}

function eventText(event: EventEnvelope): string {
	if (typeof event.payload === "string") return event.payload;
	if (isRecord(event.payload)) {
		if (event.eventType === "tool_call" && typeof event.payload.name === "string") {
			return `[tool call: ${event.payload.name}(${canonicalish(event.payload.arguments)})]`;
		}
		if (typeof event.payload.text === "string") return event.payload.text;
		if (typeof event.payload.content === "string") return event.payload.content;
		if (Array.isArray(event.payload.content)) return blocksToText(event.payload.content);
		if (isRecord(event.payload.message)) return eventText({ ...event, payload: event.payload.message });
	}
	if (event.payloadRef) return `[offloaded content: ${event.payloadRef}]`;
	return "";
}

function projectsToProviderContext(event: EventEnvelope): boolean {
	if (event.eventType !== "message" && event.eventType !== "tool_call" && event.eventType !== "tool_result") {
		return false;
	}
	return !(isRecord(event.payload) && event.payload.control === true);
}

/**
 * Layered pinned injection (design correction 2026-08-22): global contract +
 * current focus task contract in full + non-terminal task index + pending
 * goal changes. What is pinned is the RE-INJECTION MECHANISM and its
 * authority, not frozen content.
 */
export function renderPinnedLedgerLayer(ledger: TaskLedgerLike, globalContract?: TaskContract): string {
	const parts: string[] = [];
	if (globalContract) {
		parts.push(renderContract(globalContract, true));
	}
	const focus = ledger.getFocusTask();
	if (focus) {
		const sourceRefs = new Set([
			...focus.goal.verbatimSourceEventIds,
			focus.provenance.createdFromEvent,
			...focus.provenance.updatedFromEvents,
		]);
		const lines = [
			`# Current focus task ${focus.taskId} (contract v${focus.version}, status ${focus.status})`,
			`Task ref: task://${focus.taskId}/v${focus.version}`,
			`Goal: ${focus.goal.normalized}`,
			`Goal scope: ${focus.goal.scope?.join(", ") || "(none)"}`,
			`Goal exclusions: ${focus.goal.exclusions?.join(", ") || "(none)"}`,
			"## Acceptance criteria",
			...(focus.acceptanceCriteria.length > 0 ? focus.acceptanceCriteria.map((c) => `- ${c}`) : ["- (none)"]),
			"## Task constraints",
			...(focus.constraints.length > 0 ? focus.constraints.map((c) => `- [${c.kind}] ${c.text}`) : ["- (none)"]),
			"## Task permissions",
			`- allow: ${focus.permissions.allow.join(", ") || "(none)"}`,
			`- deny: ${focus.permissions.deny.join(", ") || "(none)"}`,
			`- approval required: ${focus.permissions.approvalRequired.join(", ") || "(none)"}`,
			"## Task budgets",
			...renderBudgetLines(focus.budgets),
			"## Output contract",
			focus.outputContract ?? "(none)",
			"## Blockers",
			...(focus.blockers.length > 0 ? focus.blockers.map((b) => `- ${b}`) : ["- (none)"]),
			"## Relations",
			`- parent: ${focus.relations.parentTaskId ?? "(none)"}`,
			`- depends on: ${focus.relations.dependsOn.join(", ") || "(none)"}`,
			`- supersedes: ${focus.relations.supersedes ?? "(none)"}`,
			"## Provenance",
			`- created by: ${focus.provenance.createdBy.kind}:${focus.provenance.createdBy.id} (verified=${focus.provenance.createdBy.verified})`,
			`- created at: ${focus.createdAt}`,
			`- updated at: ${focus.updatedAt}`,
			`- events: ${[...sourceRefs].filter(Boolean).join(", ") || "(none)"}`,
		];
		parts.push(lines.join("\n"));
	}
	const index = ledger.nonTerminalIndex().filter((t) => t.taskId !== focus?.taskId);
	if (index.length > 0) {
		const crossTaskConstraints = index.flatMap((entry) => {
			const task = ledger.getTask?.(entry.taskId);
			return (task?.constraints ?? []).map(
				(constraint) => `- ${entry.taskId}: [${constraint.kind}] ${constraint.text}`,
			);
		});
		if (crossTaskConstraints.length > 0) {
			parts.push(["# Cross-task constraints from other open tasks", ...crossTaskConstraints].join("\n"));
		}
		parts.push(
			[
				"# Other open tasks (index only — recall for details)",
				...index.map(
					(t) =>
						`- ${t.taskId} [${t.status}] v${t.version}: ${t.goal}${t.blockers.length ? ` (blockers: ${t.blockers.join("; ")})` : ""}`,
				),
			].join("\n"),
		);
	}
	const pending = ledger.getPendingGoalChanges();
	if (pending.length > 0) {
		parts.push(
			[
				"# Pending goal changes (unconfirmed — do not act on them)",
				...pending.map(
					(p) =>
						`- ${p.reason} (candidates: ${p.candidateTaskIds.join(", ") || "none"}; source ${p.sourceEventId})`,
				),
			].join("\n"),
		);
	}
	return parts.join("\n\n");
}

function renderBudgetLines(budgets: TaskContract["budgets"]): string[] {
	return [
		`- max tokens: ${budgets.maxTokens ?? "(none)"}`,
		`- max tool calls: ${budgets.maxToolCalls ?? "(none)"}`,
		`- max duration ms: ${budgets.maxDurationMs ?? "(none)"}`,
	];
}

function renderContract(contract: TaskContract, global = false): string {
	const lines = [
		`# ${global ? "Global Contract" : "Task Contract"} (version ${contract.version}, id ${contract.contractId})`,
		global ? `Legacy session goal (non-authoritative): ${contract.goal}` : `Goal: ${contract.goal}`,
		...(contract.derivedGoal ? [`Working goal (auto-derived, unconfirmed): ${contract.derivedGoal.text}`] : []),
		"",
		"## Acceptance criteria",
		...contract.acceptanceCriteria.map((c) => `- ${c}`),
		"",
		"## Constraints (always active)",
		...contract.constraints.map((c) => `- [${c.kind}] ${c.text}`),
		"",
		"## Permissions",
		`- allow: ${contract.permissions.allow.join(", ") || "(none)"}`,
		`- deny: ${contract.permissions.deny.join(", ") || "(none)"}`,
		`- approval required: ${contract.permissions.approvalRequired.join(", ") || "(none)"}`,
		"",
		"## Budgets",
		...renderBudgetLines(contract.budgets),
	];
	if (contract.outputContract) {
		lines.push("", `## Output contract`, contract.outputContract);
	}
	return lines.join("\n");
}

/**
 * Deterministic Current Focus View: generated by code, references only IDs
 * present in the snapshot. Never invents facts.
 */
export function buildFocusView(snapshot: StructuredSnapshot): string {
	const lines: string[] = ["## Current focus"];
	const inProgress = snapshot.tasks.filter((t) => t.state === "in_progress");
	const blocked = snapshot.tasks.filter((t) => t.state === "blocked");
	const done = snapshot.tasks.filter((t) => t.state === "done");
	for (const t of inProgress) lines.push(`- in progress: ${t.title} (${t.id})`);
	for (const t of blocked)
		lines.push(`- blocked: ${t.title} (${t.id})${t.blockers.length ? ` — blockers: ${t.blockers.join("; ")}` : ""}`);
	if (done.length > 0) lines.push(`- done: ${done.map((t) => `${t.title} (${t.id})`).join(", ")}`);
	const unresolved = snapshot.errors.filter((e) => !e.resolved);
	for (const e of unresolved) lines.push(`- unresolved error: ${e.message} (${e.id})`);
	for (const n of snapshot.nextActions) lines.push(`- next: ${n.text} (${n.id})`);
	if (snapshot.recallCatalogRefs.length > 0) {
		lines.push(`- recallable: ${snapshot.recallCatalogRefs.join(", ")}`);
	}
	return lines.join("\n");
}

function renderSnapshot(snapshot: StructuredSnapshot): string {
	const parts: string[] = [
		`# Verified state snapshot v${snapshot.snapshotVersion} (covers events through seq ${snapshot.baseEventSeq})`,
		buildFocusView(snapshot),
	];
	if (snapshot.facts.length > 0) {
		parts.push(
			"",
			"## Facts",
			...snapshot.facts.map((f) => `- ${f.verified ? "" : "[unverified] "}${f.text} (${f.id})`),
		);
	}
	if (snapshot.decisions.length > 0) {
		parts.push(
			"",
			"## Decisions",
			...snapshot.decisions.map((d) => `- ${d.text}${d.rationale ? ` — ${d.rationale}` : ""} (${d.id})`),
		);
	}
	if (snapshot.tools.length > 0) {
		parts.push(
			"",
			"## Tool states",
			...snapshot.tools.map(
				(t) =>
					`- ${t.name} [${t.toolCallId}]: ${t.state}${t.exitCode !== undefined ? ` (exit ${t.exitCode})` : ""}${t.resultRef ? ` ref ${t.resultRef}` : ""}`,
			),
		);
	}
	if (snapshot.artifacts.length > 0) {
		parts.push(
			"",
			"## Artifacts",
			...snapshot.artifacts.map(
				(artifact) =>
					`- ${artifact.kind}: ${artifact.preview} (${artifact.ref}, ${artifact.size} bytes${artifact.pinned ? ", pinned" : ""})`,
			),
		);
	}
	return parts.join("\n");
}

type SnapshotItemKind = "fact" | "decision" | "task" | "tool" | "artifact" | "error" | "next" | "recall";

interface SnapshotItemRef {
	key: string;
	kind: SnapshotItemKind;
}

function sourceOrder(snapshot: StructuredSnapshot, sourceEventIds: string[], fallback: number): number {
	const eventOrder = new Map<string, number>();
	let order = 0;
	for (const range of snapshot.sourceEventRanges) {
		for (let seq = range.fromSeq; seq <= range.toSeq; seq++) eventOrder.set(`seq:${seq}`, order++);
	}
	const explicit = sourceEventIds
		.map((id) => eventOrder.get(id))
		.filter((value): value is number => value !== undefined);
	return explicit.length > 0 ? Math.max(...explicit) : fallback;
}

function projectSnapshot(
	snapshot: StructuredSnapshot,
	budgetTokens: number,
	estimate: (text: string) => number,
): { text: string; stats: ZoneProjectionStats } {
	const emptySnapshot: StructuredSnapshot = {
		...snapshot,
		facts: [],
		decisions: [],
		tasks: [],
		tools: [],
		artifacts: [],
		errors: [],
		nextActions: [],
		recallCatalogRefs: [],
	};
	const baseTokens = estimate(renderSnapshot(emptySnapshot));
	if (baseTokens > budgetTokens) throw new PromptBudgetExceededError("snapshot", budgetTokens, baseTokens);

	let order = 0;
	const item = (
		kind: SnapshotItemKind,
		id: string,
		text: string,
		priority: number,
		protectedItem: boolean,
		sourceEventIds: string[] = [],
	) => ({
		id: `${kind}:${id}`,
		value: { key: id, kind } satisfies SnapshotItemRef,
		tokens: Math.max(1, estimate(text)),
		priority,
		protected: protectedItem,
		order: sourceOrder(snapshot, sourceEventIds, order++),
	});
	const candidates = [
		...snapshot.facts.map((fact) =>
			item(
				"fact",
				fact.id,
				`- ${fact.verified ? "" : "[unverified] "}${fact.text} (${fact.id})`,
				fact.verified ? 60 : 30,
				false,
				fact.provenance.sourceEventIds,
			),
		),
		...snapshot.decisions.map((decision) =>
			item(
				"decision",
				decision.id,
				`- ${decision.text}${decision.rationale ? ` — ${decision.rationale}` : ""} (${decision.id})`,
				70,
				false,
				decision.provenance.sourceEventIds,
			),
		),
		...snapshot.tasks.map((task) =>
			item(
				"task",
				task.id,
				`${task.title} ${task.state} ${task.blockers.join(" ")}`,
				task.state === "in_progress" ? 100 : task.state === "blocked" ? 95 : task.state === "pending" ? 75 : 10,
				task.state === "in_progress" || task.state === "blocked",
				task.provenance.sourceEventIds,
			),
		),
		...snapshot.tools.map((tool) => {
			const open = tool.state !== "succeeded";
			return item(
				"tool",
				tool.toolCallId,
				`${tool.name} ${tool.state} ${tool.resultRef ?? ""}`,
				open ? 100 : 35,
				open,
				tool.provenance.sourceEventIds,
			);
		}),
		...snapshot.artifacts.map((artifact) =>
			item(
				"artifact",
				artifact.ref,
				`${artifact.kind} ${artifact.preview} ${artifact.ref}`,
				artifact.pinned ? 100 : 40,
				artifact.pinned,
				artifact.provenance.sourceEventIds,
			),
		),
		...snapshot.errors.map((error) =>
			item(
				"error",
				error.id,
				error.message,
				error.resolved ? 10 : 100,
				!error.resolved,
				error.provenance.sourceEventIds,
			),
		),
		...snapshot.nextActions.map((next) =>
			item("next", next.id, next.text, 85, false, next.provenance.sourceEventIds),
		),
		...snapshot.recallCatalogRefs.map((ref) => item("recall", ref, ref, 50, false)),
	];
	let selection = selectBudgetedItems("snapshot", candidates, Math.max(0, budgetTokens - baseTokens));
	const selected = new Set(selection.selected.map((selectedItem) => `${selectedItem.kind}:${selectedItem.key}`));
	const materialize = (): StructuredSnapshot => ({
		...snapshot,
		facts: snapshot.facts.filter((value) => selected.has(`fact:${value.id}`)),
		decisions: snapshot.decisions.filter((value) => selected.has(`decision:${value.id}`)),
		tasks: snapshot.tasks.filter((value) => selected.has(`task:${value.id}`)),
		tools: snapshot.tools.filter((value) => selected.has(`tool:${value.toolCallId}`)),
		artifacts: snapshot.artifacts.filter((value) => selected.has(`artifact:${value.ref}`)),
		errors: snapshot.errors.filter((value) => selected.has(`error:${value.id}`)),
		nextActions: snapshot.nextActions.filter((value) => selected.has(`next:${value.id}`)),
		recallCatalogRefs: snapshot.recallCatalogRefs.filter((value) => selected.has(`recall:${value}`)),
	});

	let text = renderSnapshot(materialize());
	let tokens = estimate(text);
	if (tokens > budgetTokens) {
		const optionalSelected = candidates
			.filter((candidate) => selected.has(candidate.id) && !candidate.protected)
			.sort(
				(left, right) =>
					left.priority - right.priority || left.order - right.order || right.id.localeCompare(left.id),
			);
		for (const candidate of optionalSelected) {
			selected.delete(candidate.id);
			text = renderSnapshot(materialize());
			tokens = estimate(text);
			if (tokens <= budgetTokens) break;
		}
	}
	if (tokens > budgetTokens) throw new PromptBudgetExceededError("snapshot", budgetTokens, tokens);
	selection = {
		...selection,
		droppedItems: candidates.length - selected.size,
		usedTokens: tokens,
	};
	return {
		text,
		stats: {
			zone: "snapshot",
			budgetTokens,
			usedTokens: tokens,
			droppedItems: selection.droppedItems,
			protectedItems: selection.protectedItems,
		},
	};
}

function renderTail(events: EventEnvelope[]): string {
	return events
		.map((e) => {
			const text = eventText(e);
			return text ? `[${e.seq} ${e.eventType}] ${text}` : `[${e.seq} ${e.eventType}]`;
		})
		.join("\n\n");
}

function tailImageTokens(events: EventEnvelope[]): number {
	return events.reduce((sum, event) => {
		const payload = event.payload;
		if (!isRecord(payload)) return sum;
		const imageCount =
			typeof payload.imageCount === "number" ? payload.imageCount : payload.hasImages === true ? 1 : 0;
		return sum + imageCount * 1200;
	}, 0);
}

function projectTail(
	events: EventEnvelope[],
	budgetTokens: number,
	estimate: (text: string) => number,
): { events: EventEnvelope[]; stats: ZoneProjectionStats } {
	const groups = buildAtomicGroups(events);
	const byEventId = new Map(events.map((event) => [event.eventId, event]));
	const candidates = groups.map((group, order) => {
		const members = group.eventIds.map((eventId) => byEventId.get(eventId)).filter((event) => event !== undefined);
		return {
			id: group.groupId,
			value: members,
			tokens: estimate(renderTail(members)) + tailImageTokens(members),
			priority: 100,
			protected: !group.closed,
			order,
		};
	});
	const selection = selectBudgetedItems("recentTail", candidates, budgetTokens);
	const selectedGroups = new Set(selection.selected);
	const materialize = () => {
		const selectedIds = new Set([...selectedGroups].flat().map((event) => event.eventId));
		return events.filter((event) => selectedIds.has(event.eventId));
	};
	let selectedEvents = materialize();
	let usedTokens =
		selectedEvents.length > 0 ? estimate(renderTail(selectedEvents)) + tailImageTokens(selectedEvents) : 0;
	if (usedTokens > budgetTokens) {
		for (const candidate of candidates
			.filter((candidate) => selectedGroups.has(candidate.value) && !candidate.protected)
			.sort((left, right) => left.order - right.order || left.id.localeCompare(right.id))) {
			selectedGroups.delete(candidate.value);
			selectedEvents = materialize();
			usedTokens =
				selectedEvents.length > 0 ? estimate(renderTail(selectedEvents)) + tailImageTokens(selectedEvents) : 0;
			if (usedTokens <= budgetTokens) break;
		}
	}
	if (usedTokens > budgetTokens) throw new PromptBudgetExceededError("recentTail", budgetTokens, usedTokens);
	return {
		events: selectedEvents,
		stats: {
			zone: "recentTail",
			budgetTokens,
			usedTokens,
			droppedItems: candidates.length - selectedGroups.size,
			protectedItems: selection.protectedItems,
		},
	};
}

function projectLossyText(
	zone: "narrative" | "recallGuide",
	text: string,
	budgetTokens: number,
	estimate: (text: string) => number,
): { text: string; stats: ZoneProjectionStats } {
	const projected = truncateTextToBudget(text, budgetTokens, estimate);
	return {
		text: projected.text,
		stats: {
			zone,
			budgetTokens,
			usedTokens: projected.tokens,
			droppedItems: projected.truncated ? 1 : 0,
			protectedItems: 0,
		},
	};
}

export function buildPrompt(input: PromptBuilderInput): BuiltPrompt {
	const estimate = input.estimateTextTokens ?? defaultEstimate;
	const budgets: PromptZoneBudgets = { ...DEFAULT_PROMPT_ZONE_BUDGETS, ...input.zoneBudgets };
	const providerTailEvents = input.tailEvents.filter(projectsToProviderContext);
	const sections: PromptSection[] = [];
	const projectionStats: ZoneProjectionStats[] = [];
	const push = (zone: ZoneKind, text: string) => {
		if (text.length === 0) return;
		sections.push({ zone, text, tokens: estimate(text) });
	};

	// Frozen order: contract → snapshot → narrative → recall guide → tail → input → recall.
	// With a task ledger, the contract zone is the live pinned projection so its
	// full token cost participates in both runtime projection and accounting.
	if (input.ledger) push("contract", renderPinnedLedgerLayer(input.ledger, input.contract));
	else if (input.contract) push("contract", renderContract(input.contract));
	if (input.snapshot) {
		const projected = projectSnapshot(input.snapshot, budgets.snapshot, estimate);
		push("snapshot", projected.text);
		projectionStats.push(projected.stats);
	} else {
		projectionStats.push({
			zone: "snapshot",
			budgetTokens: budgets.snapshot,
			usedTokens: 0,
			droppedItems: 0,
			protectedItems: 0,
		});
	}
	const narrative = input.narrative ?? input.snapshot?.narrative;
	const projectedNarrative = projectLossyText(
		"narrative",
		narrative ? `# Progress so far\n${narrative}` : "",
		budgets.narrative,
		estimate,
	);
	push("narrative", projectedNarrative.text);
	projectionStats.push(projectedNarrative.stats);
	const projectedRecallGuide = projectLossyText("recallGuide", input.recallGuide ?? "", budgets.recallGuide, estimate);
	push("recallGuide", projectedRecallGuide.text);
	projectionStats.push(projectedRecallGuide.stats);
	const projectedTail =
		input.enforceRecentTailBudget === false
			? {
					events: providerTailEvents,
					stats: {
						zone: "recentTail" as const,
						budgetTokens: budgets.recentTail,
						usedTokens:
							providerTailEvents.length > 0
								? estimate(renderTail(providerTailEvents)) + tailImageTokens(providerTailEvents)
								: 0,
						droppedItems: 0,
						protectedItems: buildAtomicGroups(providerTailEvents).filter((group) => !group.closed).length,
					},
				}
			: projectTail(providerTailEvents, budgets.recentTail, estimate);
	if (projectedTail.events.length > 0) push("recentTail", renderTail(projectedTail.events));
	projectionStats.push(projectedTail.stats);
	push("currentInput", input.currentInput);
	const exactRecallText = input.exactRecall.join("\n\n");
	const exactRecallTokens = estimate(exactRecallText);
	if (exactRecallTokens > budgets.exactRecall) {
		throw new PromptBudgetExceededError("exactRecall", budgets.exactRecall, exactRecallTokens);
	}
	push("exactRecall", exactRecallText);
	projectionStats.push({
		zone: "exactRecall",
		budgetTokens: budgets.exactRecall,
		usedTokens: exactRecallTokens,
		droppedItems: 0,
		protectedItems: input.exactRecall.length,
	});

	const zoneTokens = (zone: ZoneKind) => sections.filter((s) => s.zone === zone).reduce((sum, s) => sum + s.tokens, 0);
	const tokenStats: TokenStats = {
		system: estimate(input.systemPrompt),
		tools: input.toolsTokenEstimate ?? 0,
		contract: zoneTokens("contract"),
		snapshot: zoneTokens("snapshot"),
		narrative: zoneTokens("narrative"),
		recall: zoneTokens("recallGuide") + zoneTokens("exactRecall"),
		recentTail: zoneTokens("recentTail") + tailImageTokens(projectedTail.events),
		currentInput: zoneTokens("currentInput"),
		outputReserve: input.outputReserveTokens ?? 0,
		total: 0,
	};
	tokenStats.total =
		tokenStats.system +
		tokenStats.tools +
		tokenStats.contract +
		tokenStats.snapshot +
		tokenStats.narrative +
		tokenStats.recall +
		tokenStats.recentTail +
		tokenStats.currentInput +
		tokenStats.outputReserve;

	return { systemPrompt: input.systemPrompt, sections, tokenStats, projectionStats };
}

/**
 * Compaction-off passthrough: the original history path, untouched.
 */
export function buildPassthroughPrompt<TMessage>(
	systemPrompt: string,
	messages: TMessage[],
): { systemPrompt: string; messages: TMessage[] } {
	return { systemPrompt, messages };
}
